import type { DeviceListItem, DeviceListResponse, IntegrationOption, UserListItem, UserListResponse } from "../types/api";

const testInventorySource: IntegrationOption = {
  id: "atlas-test-lab",
  name: "Atlas Test Lab",
};

const testUsers: UserListItem[] = [
  {
    id: "test-user-01",
    display_name: "Jordan Lee",
    email: "jordan.lee+test@sysatlas.dev",
    source_provider: testInventorySource.name,
    title: "IT Coordinator",
    department: "Operations",
    lifecycle_state: "active",
    account_status: "active",
    device_count: 2,
    created_at: "2026-03-21T14:05:00Z",
    last_activity_at: "2026-03-27T13:42:00Z",
    last_synced_at: "2026-03-27T13:55:00Z",
  },
  {
    id: "test-user-02",
    display_name: "Avery Brooks",
    email: "avery.brooks+test@sysatlas.dev",
    source_provider: testInventorySource.name,
    title: "Systems Analyst",
    department: "Infrastructure",
    lifecycle_state: "active",
    account_status: "active",
    device_count: 1,
    created_at: "2026-03-22T10:30:00Z",
    last_activity_at: "2026-03-27T12:18:00Z",
    last_synced_at: "2026-03-27T13:55:00Z",
  },
  {
    id: "test-user-03",
    display_name: "Morgan Patel",
    email: "morgan.patel+test@sysatlas.dev",
    source_provider: testInventorySource.name,
    title: "Support Lead",
    department: "Service Desk",
    lifecycle_state: "offboarding",
    account_status: "disabled",
    device_count: 3,
    created_at: "2026-03-24T09:15:00Z",
    last_activity_at: "2026-03-24T17:05:00Z",
    last_synced_at: "2026-03-27T13:55:00Z",
  },
  {
    id: "test-user-04",
    display_name: "Taylor Nguyen",
    email: "taylor.nguyen+test@sysatlas.dev",
    source_provider: testInventorySource.name,
    title: "Security Engineer",
    department: "Security",
    lifecycle_state: "active",
    account_status: "active",
    device_count: 2,
    created_at: "2026-03-25T11:20:00Z",
    last_activity_at: "2026-03-27T11:09:00Z",
    last_synced_at: "2026-03-27T13:55:00Z",
  },
  {
    id: "test-user-05",
    display_name: "Casey Morgan",
    email: "casey.morgan+test@sysatlas.dev",
    source_provider: testInventorySource.name,
    title: "Finance Manager",
    department: "Finance",
    lifecycle_state: "leave",
    account_status: "disabled",
    device_count: 0,
    created_at: "2026-03-27T08:40:00Z",
    last_activity_at: "2026-03-20T09:30:00Z",
    last_synced_at: "2026-03-27T13:55:00Z",
  },
];

const testDevices: DeviceListItem[] = [
  {
    id: "test-device-01",
    device_name: "ATLAS-LT-001",
    platform: "Windows 11",
    manufacturer: "Dell",
    model: "Latitude 7450",
    serial_number: "DL7450-TST-001",
    source_provider: testInventorySource.name,
    ownership: "Corporate",
    compliance_state: "compliant",
    management_state: "managed",
    primary_user_email: "jordan.lee+test@sysatlas.dev",
    lifecycle_state: "active",
    created_at: "2026-03-21T16:25:00Z",
    last_check_in_at: "2026-03-27T13:36:00Z",
  },
  {
    id: "test-device-02",
    device_name: "ATLAS-MBP-014",
    platform: "macOS",
    manufacturer: "Apple",
    model: "MacBook Pro 14",
    serial_number: "MBP14-TST-014",
    source_provider: testInventorySource.name,
    ownership: "Corporate",
    compliance_state: "compliant",
    management_state: "managed",
    primary_user_email: "avery.brooks+test@sysatlas.dev",
    lifecycle_state: "active",
    created_at: "2026-03-22T13:10:00Z",
    last_check_in_at: "2026-03-27T12:52:00Z",
  },
  {
    id: "test-device-03",
    device_name: "ATLAS-IPH-077",
    platform: "iOS",
    manufacturer: "Apple",
    model: "iPhone 15",
    serial_number: "IPH15-TST-077",
    source_provider: testInventorySource.name,
    ownership: "Corporate",
    compliance_state: "action_required",
    management_state: "managed",
    primary_user_email: "morgan.patel+test@sysatlas.dev",
    lifecycle_state: "active",
    created_at: "2026-03-24T15:05:00Z",
    last_check_in_at: "2026-03-26T21:14:00Z",
  },
  {
    id: "test-device-04",
    device_name: "ATLAS-SUR-022",
    platform: "Windows 11",
    manufacturer: "Microsoft",
    model: "Surface Laptop 6",
    serial_number: "SUR6-TST-022",
    source_provider: testInventorySource.name,
    ownership: "Corporate",
    compliance_state: "unknown",
    management_state: "pending",
    primary_user_email: "taylor.nguyen+test@sysatlas.dev",
    lifecycle_state: "staging",
    created_at: "2026-03-25T17:40:00Z",
    last_check_in_at: "2026-03-25T16:48:00Z",
  },
  {
    id: "test-device-05",
    device_name: "ATLAS-PIX-019",
    platform: "Android",
    manufacturer: "Google",
    model: "Pixel 8",
    serial_number: "PIX8-TST-019",
    source_provider: testInventorySource.name,
    ownership: "BYOD",
    compliance_state: "action_required",
    management_state: "managed",
    primary_user_email: "jordan.lee+test@sysatlas.dev",
    lifecycle_state: "active",
    created_at: "2026-03-26T09:50:00Z",
    last_check_in_at: "2026-03-27T08:07:00Z",
  },
  {
    id: "test-device-06",
    device_name: "ATLAS-KSK-003",
    platform: "Windows 10",
    manufacturer: "HP",
    model: "Pro Mini 400",
    serial_number: null,
    source_provider: testInventorySource.name,
    ownership: "Corporate",
    compliance_state: "compliant",
    management_state: "managed",
    primary_user_email: null,
    lifecycle_state: "active",
    created_at: "2026-03-27T07:35:00Z",
    last_check_in_at: "2026-03-27T10:24:00Z",
  },
];

export function getTestUsersResponse(): UserListResponse {
  return {
    items: testUsers.map((item) => ({ ...item })),
    source_status: {
      module: "users",
      has_configured_source: true,
      configured_sources: [{ ...testInventorySource }],
      suggested_sources: [{ ...testInventorySource }],
      empty_state_message: "Test mode is active.",
    },
    stats: {
      total_users: testUsers.length,
      active_users: testUsers.filter((item) => item.account_status === "active").length,
      offboarding_users: testUsers.filter((item) => item.lifecycle_state === "offboarding").length,
      connected_sources: 1,
    },
  };
}

export function getTestDevicesResponse(): DeviceListResponse {
  return {
    items: testDevices.map((item) => ({ ...item })),
    source_status: {
      module: "devices",
      has_configured_source: true,
      configured_sources: [{ ...testInventorySource }],
      suggested_sources: [{ ...testInventorySource }],
      empty_state_message: "Test mode is active.",
    },
    stats: {
      total_devices: testDevices.length,
      compliant_devices: testDevices.filter((item) => item.compliance_state === "compliant").length,
      action_required_devices: testDevices.filter((item) => item.compliance_state !== "compliant").length,
      connected_sources: 1,
    },
  };
}
